# Generated by Django 3.0.7 on 2020-06-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardManage', '0002_remove_book_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publish',
            field=models.CharField(default='人民出版社', max_length=32),
        ),
    ]
